site_name: pyOPENDART

site_author: Seonghyeon Kim
site_description: 전자공시시스템 DART 파이썬 API (for Humans)

repo_name: NovemberOscar/pyOPENDART
repo_url: https://github.com/NovemberOscar/pyOPENDART
edit_uri: ""

copyright: Copyright &copy; 2021- Seonghyeon Kim

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.details
  - admonition
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - toc:
      permalink: true

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
  language: kr

nav:
  - Home: index.md
  - Corporation: corporation.md
  - Clients:
    - 공시정보: clients/disclosure.md
    - 사업보고서 주요정보: clients/business_report.md
    - 상장기업 재무정보: clients/financial_statement.md
    - 지분공시 종합정보: clients/shareholder_report.md
    - 원본파일 다운로드: clients/download.md
  - Advanced Usage:
    - 타임아웃 설정하기: advanced/timeout.md
    - 고급 데이터프레임 클라이언트 옵션: advanced/df_client.md
    - HTTPX 클라이언트 사용하기: advanced/httpx.md
