[tool.poetry]
name = "pyOPENDART"
version = "0.1.0"
description = "전자공시 DART Python API"
authors = ["Seonghyeon Kim <self@seonghyeon.dev>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"
requests = "^2.25.1"
furl = "^2.1.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
